### ISSUE TITLE
“티빙에만 있는재미” 고정 이미지 새로고침시 랜덤 전환

### ISSUE THREAD

**Issue by 1101x** [FRONTENDSCHOOL8/JFAM#2]

**Comment by yeseul0000** [comment]
이거는 제가 생각을 해봤는데요.
일단 배경으로 들어가는 이미지이다 보니까 랜덤 전환을 어떻게 해야할지 감이 안 잡혀요..
아시는 분 있으시면 확인 부탁드릴게요!

**Comment by yeseul0000** [comment]
저번에 회의했던 대로 제외할게요! 다른 의견 있으면 언제든 다시 얘기해주세요~!!
